GOOGLE_API_KEY = "AQ.Ab8RN6JK63zQuhyS-8yNazK1TaLGz3PsRFnfK1lM8Tn6wEIt5A"
GEMINI_API_KEY = "AQ.Ab8RN6JK63zQuhyS-8yNazK1TaLGz3PsRFnfK1lM8Tn6wEIt5A"

[default]
GOOGLE_API_KEY = "AQ.Ab8RN6JK63zQuhyS-8yNazK1TaLGz3PsRFnfK1lM8Tn6wEIt5A"
GEMINI_API_KEY = "AQ.Ab8RN6JK63zQuhyS-8yNazK1TaLGz3PsRFnfK1lM8Tn6wEIt5A"
